version: "3.3"

services:
  auth:
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/auth.Dockerfile
    ports:
      - "8010:8010"
      - "8011:8011"
    volumes:
      - type: bind
        source: /var/log
        target: /var/log
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure

  user:
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/user.Dockerfile
    ports:
      - "8020:8020"
      - "8021:8021"
    volumes:
      - type: bind
        source: /home/ubuntu/frontend/static/public/images/user
        target: /images
      - type: bind
        source: /var/log
        target: /var/log
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure


  creator:
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/creator.Dockerfile
    ports:
      - "8030:8030"
      - "8031:8031"
    volumes:
      - type: bind
        source: /home/ubuntu/frontend/static/public/images/user
        target: /images
      - type: bind
        source: /var/log
        target: /var/log
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /home/ubuntu/db_data
        target: /var/lib/postgresql/data
      - type: bind
        source: /usr/share/postgresql/14/tsearch_data
        target: /usr/share/postgresql/14/tsearch_data

  main:
    env_file:
      - .env
    depends_on:
      - postgres
      - auth
      - user
      - creator
    build:
      context: .
      dockerfile: build/main.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: /home/ubuntu/frontend/static/public/images/user
        target: /images
      - type: bind
        source: /var/log
        target: /var/log
